### ISSUE TITLE
为什么一直显示检测更新

### ISSUE THREAD

**Issue by P3TERX** [ylqjgm/LoveKKComment#1]
![snipaste20181113_141247](https://user-images.githubusercontent.com/25927179/48394390-63a4a500-e74e-11e8-8346-4ba431af35e3.png)
虽然不影响使用

**Comment by ylqjgm** [comment]
额，因为更新服务器已经挂了，准备下个版本修复这个问题

**Comment by ylqjgm** [comment]
> ![snipaste20181113_141247](https://user-images.githubusercontent.com/25927179/48394390-63a4a500-e74e-11e8-8346-4ba431af35e3.png)
> 虽然不影响使用

已经更新了，去除了版本检测功能

**Comment by P3TERX** [comment]
![tim 20180116175226](https://user-images.githubusercontent.com/25927179/50900886-83f09780-1451-11e9-9cfe-cf6bd5996fb1.jpg)
