### ISSUE TITLE
smtp发送邮件求更新成异步

### ISSUE THREAD

**Issue by ifeevel** [ylqjgm/LoveKKComment#2]
因为国外vps的原因，点击评论后等待时间太长

**Comment by ylqjgm** [comment]
异步的是开发版拥有的新功能，正式版并没有异步功能，所以目前来说并不适合开发异步版本啊，毕竟很多人用的还是正式版啊

**Comment by ifeevel** [comment]
> 异步的是开发版拥有的新功能，正式版并没有异步功能，所以目前来说并不适合开发异步版本啊，毕竟很多人用的还是正式版啊

这样啊，理解理解，感谢回复 目前在用哈哈

**Comment by ylqjgm** [comment]
没什么，你的这个建议还是很不错的，我考虑下，有空再开发一个版本，或者看看有没有什么办法能够兼容

**Comment by ylqjgm** [comment]
> > 异步的是开发版拥有的新功能，正式版并没有异步功能，所以目前来说并不适合开发异步版本啊，毕竟很多人用的还是正式版啊
> 
> 这样啊，理解理解，感谢回复 目前在用哈哈

插件已经更新了，支持了异步模式，可以更新尝试下
