### ISSUE TITLE
关闭找回密码警告

### ISSUE THREAD

**Issue by ghost** [ylqjgm/LoveKKComment#4]
typecho：1.2 (18.10.23)
LoveKKComment：1.0.5

复现过程：关闭找回密码

报错信息：Warning: in_array() expects parameter 2 to be array, null given in xxx/usr/plugins/LoveKKComment/Plugin.php on line 801

**Comment by ylqjgm** [comment]
小bug，不影响使用，无需理会，下个版本修复
