### ISSUE TITLE
提交评论出错了

### ISSUE THREAD

**Issue by lepig** [ylqjgm/LoveKKComment#7]
提交评论后出现
```
Too few arguments to function Widget_Abstract::__construct(), 0 passed in /srv/www/typecho.example.com/var/Helper.php on line 57 and at least 2 expected
```

刚开始配置的是阿里云的，也出现这个错。后来配置成smtp，提示SSL不行，后来根据提示设置为TLS 587端口就开启成功了。

**Comment by lepig** [comment]
然后我禁用这个插件 就可以正常评论了。

**Comment by hack2012** [comment]
我也有这个问题，请帮忙解决一下兄弟。 php7.3

**Comment by hack2012** [comment]
> 提交评论后出现
> 
> ```
> Too few arguments to function Widget_Abstract::__construct(), 0 passed in /srv/www/typecho.example.com/var/Helper.php on line 57 and at least 2 expected
> ```
> 
> 刚开始配置的是阿里云的，也出现这个错。后来配置成smtp，提示SSL不行，后来根据提示设置为TLS 587端口就开启成功了。

解决了，重新下载Plugin.php替换原来就行了。

**Comment by lepig** [comment]
> > 提交评论后出现
> > ```
> > Too few arguments to function Widget_Abstract::__construct(), 0 passed in /srv/www/typecho.example.com/var/Helper.php on line 57 and at least 2 expected
> > ```
> > 
> > 
> > 刚开始配置的是阿里云的，也出现这个错。后来配置成smtp，提示SSL不行，后来根据提示设置为TLS 587端口就开启成功了。
> 
> 解决了，重新下载Plugin.php替换原来就行了。

谢谢回复。 不过我现在用别的评论插件了，没有用这个了。也满足需求了。
